self.treeview = ttk.Treeview(self.window, columns=("pos","size","color","id"))
self.treeview.heading("#0", text="name")
self.treeview.heading("pos", text="Position")
self.treeview.heading("size", text="Size")
self.treeview.heading("color", text="Color")
self.treeview.heading("id", text="ID")
self.treeview.grid(row=0, column=0, sticky="NESW")